version: '3'
services:
  borg:
    container_name: borg
    hostname: borg
    build: .
    ports:
      - "222:22"
    environment:
      - BORG_AUTHORIZED_KEYS=<ssh_authorized_key>
      - BORG_UID=<uid>
      - BORG_GID=<gid>
      - BORG_VERSION=<borg version>
    restart: unless-stopped
    volumes:
      - /var/backups/borg:/var/backups/borg
